// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkRyHX_Um_B2AZJ8_0BEGNDPZZR96sSh8',
    appId: '1:189786191511:web:08cec5181a38ce56015bd2',
    messagingSenderId: '189786191511',
    projectId: 'app-cine-8a3e6',
    authDomain: 'app-cine-8a3e6.firebaseapp.com',
    storageBucket: 'app-cine-8a3e6.firebasestorage.app',
    measurementId: 'G-ZXS9Y7KR1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7NVbWuaNhsfbjxBfIBg9LjM6o788WBI',
    appId: '1:189786191511:android:23eafad25ab6e43f015bd2',
    messagingSenderId: '189786191511',
    projectId: 'app-cine-8a3e6',
    storageBucket: 'app-cine-8a3e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPodvVMdWjDxrpSD-j5gP3Pew6eHM_S44',
    appId: '1:189786191511:ios:e6cee4cadb1b574f015bd2',
    messagingSenderId: '189786191511',
    projectId: 'app-cine-8a3e6',
    storageBucket: 'app-cine-8a3e6.firebasestorage.app',
    iosBundleId: 'com.example.appCine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPodvVMdWjDxrpSD-j5gP3Pew6eHM_S44',
    appId: '1:189786191511:ios:e6cee4cadb1b574f015bd2',
    messagingSenderId: '189786191511',
    projectId: 'app-cine-8a3e6',
    storageBucket: 'app-cine-8a3e6.firebasestorage.app',
    iosBundleId: 'com.example.appCine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkRyHX_Um_B2AZJ8_0BEGNDPZZR96sSh8',
    appId: '1:189786191511:web:663fe29b35878925015bd2',
    messagingSenderId: '189786191511',
    projectId: 'app-cine-8a3e6',
    authDomain: 'app-cine-8a3e6.firebaseapp.com',
    storageBucket: 'app-cine-8a3e6.firebasestorage.app',
    measurementId: 'G-2193S52BYH',
  );
}
